import { useEffect } from 'react';
import { ACCESS_CATALOG, ACCESS_COLLECTION_SIZE, ACCESS_RARITY_ORDER } from '../data/accessCatalog';
import { ACTIVATION_COST, ALPHA_PLOT_TIERS, DURATION_PRESETS, EARLY_EXIT_SHARE, PLOT_TIERS, RARITIES, REF_RATE, WATER_COST_PER_STEP } from '../data/economy';
import { HC_PER_CHECKPOINT, MAX_FARMER_LEVEL, XP_PER_CHECKPOINT, XP_PER_LEVEL } from '../data/farmerProgression';
import { FAST_TIME_ENABLED } from '../lib/clock';
import './field-guide.css';

const chapters = [['start','The short version'],['farmer','Your farmer'],['rarity','Traits & rarity'],['grow','Plant, care, harvest'],['numbers','The numbers'],['land','Room to grow'],['access','Club access'],['status','Project status'],['faq','Common questions']] as const;
const fmt = (n: number) => new Intl.NumberFormat('en-US', { maximumFractionDigits: 3 }).format(n);

export function FieldGuide({ go }: { go: (path: string) => void }) {
  useEffect(() => { const title = document.title; document.title = 'Field Guide | Cloud 9 Farm Club'; return () => { document.title = title; }; }, []);
  return <main className="guide">
    <header className="guide-header"><button onClick={() => go('/')}>☁ CLOUD 9 FARM CLUB</button><nav aria-label="Site navigation"><button onClick={() => go('/')}>The farm</button><button onClick={() => go('/whitelist')}>Club access ↗</button></nav></header>
    <div className="guide-heading"><span>THE CLUB HANDBOOK · DEMO EDITION</span><h1>Field Guide</h1><p>A little knowledge. A better grow.<br/>Understand your farmer, follow the numbers, and know what is ready today.</p></div>
    <div className="guide-layout"><aside><nav aria-label="Guide chapters">{chapters.map(([id, label], i) => <button key={id} onClick={() => { const section = document.getElementById(`guide-${id}`); section?.scrollIntoView({ behavior: 'smooth' }); section?.focus({ preventScroll: true }); }}><span>{String(i + 1).padStart(2, '0')}</span>{label}</button>)}</nav></aside>
    <article>
      <div className="guide-notice"><strong>Playable local demo</strong><p>Game balances and progress live in this browser. No real funds, live NFT mint, or blockchain settlement is connected. The figures below describe current demo rules and may change before launch.</p><small>{FAST_TIME_ENABLED ? 'This build uses six-second checkpoints for playtesting.' : 'This build uses six-hour checkpoints.'}</small></div>
      <section id="guide-start" tabIndex={-1}><span className="guide-kicker">01 / START HERE</span><h2>The short version</h2><p>Cloud 9 Farm Club is a farming game built around a roster of growers. Choose a farmer, plant their specialty in an available bed, keep the crop watered, and harvest. Deliver harvested inventory to simulated customers for HC game credits.</p><div className="guide-cycle">Choose a farmer → Plant → Care → Harvest → Deliver</div><p>The playable world currently uses the Cedar Hollow setting. Recruiting a farmer in the demo adds a local character; it does not mint or reserve an NFT.</p></section>
      <section id="guide-farmer" tabIndex={-1}><span className="guide-kicker">02 / YOUR ROSTER</span><h2>Meet your farmer</h2><p>The current catalog contains {ACCESS_COLLECTION_SIZE} identities. Each maps to a strain specialty and a rarity. An activated farmer can run one crop at a time and grows their assigned specialty.</p><p>Activation costs {fmt(ACTIVATION_COST)} demo HC. Farmer XP persists between crops in this browser. Each new grow snapshots the farmer’s XP, so later XP gains do not retroactively increase that crop’s output.</p><div className="guide-note"><strong>Art direction · not finalized</strong><p>Simple pixel farmers are the proposed collection style. Final outfits, accessories, trait distribution, and production NFT ownership benefits have not been announced.</p></div></section>
      <section id="guide-rarity" tabIndex={-1}><span className="guide-kicker">03 / APPEARANCE & ABILITY</span><h2>Traits and rarity</h2><p>In the current demo, rarity changes crop output. A strain’s growth modifier and a farmer’s XP also affect the result. Proposed cosmetic accessories do not establish additional gameplay bonuses.</p><div className="guide-table"><table><caption>Current catalog and gameplay multipliers</caption><thead><tr><th>Rarity</th><th>Farmers</th><th>Output factor</th></tr></thead><tbody>{ACCESS_RARITY_ORDER.map(rarity => <tr key={rarity}><th>{rarity}</th><td>{ACCESS_CATALOG.filter(f => f.rarity === rarity).length}</td><td>{RARITIES[rarity].multiplier}×</td></tr>)}</tbody></table></div><p>These are the current catalog counts, not a promise of final NFT art traits or mint odds.</p></section>
      <section id="guide-grow" tabIndex={-1}><span className="guide-kicker">04 / THE GROWING CYCLE</span><h2>Plant, care, harvest</h2><p>A normal checkpoint lasts six hours. Playtest builds compress it to six seconds. Output accrues at completed checkpoints; maturity rewards arrive when the full term is successfully settled.</p><p>Manual water drops by 25 points per checkpoint: below 50 is thirsty, and zero is wilting. Eight checkpoints without care cause crop failure if the crop has not already finished sooner. In normal time, a crop starting at full water wilts after 24 hours and fails at 48 hours without care.</p><p>Manual watering costs 40 HC. Irrigation reserves {WATER_COST_PER_STEP} HC per checkpoint up front and maintains full water. Unused irrigation funds are refunded at settlement. Watering cannot revive a crop that already failed.</p><p>Early exit pays {EARLY_EXIT_SHARE * 100}% of your accrued base crop output, without the maturity multiplier or completion XP/HC. Failure pays no crop output or maturity rewards. Previously harvested inventory and earned farmer XP remain yours.</p><p>Automatic collection settles completed or failed crops while the game runs and catches up when reopened. It can be turned off in the Journal. It does not replant.</p></section>
      <section id="guide-numbers" tabIndex={-1}><span className="guide-kicker">05 / FOLLOW THE NUMBERS</span><h2>Output, XP, and credits</h2><p>Crop grams are game inventory. HC is a local game credit; farmer XP controls progression. None is a promise of cash income.</p><div className="guide-formula">Base grams per checkpoint = {REF_RATE} × rarity × XP factor × land factor × strain factor × water factor</div><p>At full water, the water factor is 1. Thirst reduces output. Successful maturity multiplies accumulated base output by the selected term’s completion factor. An owner-operated grow retains all that crop output.</p><div className="guide-table"><table><caption>Successful completion, before the farmer XP cap</caption><thead><tr><th>Normal term</th><th>Checkpoints</th><th>Crop factor</th><th>XP</th><th>HC</th></tr></thead><tbody>{Object.values(DURATION_PRESETS).map(p => <tr key={p.label}><th>{p.label}</th><td>{p.steps}</td><td>{p.maturityMultiplier}×</td><td>{p.steps * XP_PER_CHECKPOINT}</td><td>{p.steps * HC_PER_CHECKPOINT}</td></tr>)}</tbody></table></div>
      <div className="guide-note"><strong>Worked example · assumed factors</strong><p>Assume an owner-operated 24-hour grow with every base factor equal to 1 and full water throughout. Base output: {REF_RATE} × {DURATION_PRESETS['24h'].steps} = {REF_RATE * DURATION_PRESETS['24h'].steps}g. Mature output: {fmt(REF_RATE * DURATION_PRESETS['24h'].steps * DURATION_PRESETS['24h'].maturityMultiplier)}g. Completion awards {DURATION_PRESETS['24h'].steps * XP_PER_CHECKPOINT} XP before the cap and {DURATION_PRESETS['24h'].steps * HC_PER_CHECKPOINT} HC. Irrigation reserves {DURATION_PRESETS['24h'].steps * WATER_COST_PER_STEP} HC, so the completion HC minus irrigation cost is {DURATION_PRESETS['24h'].steps * (HC_PER_CHECKPOINT - WATER_COST_PER_STEP)} HC, excluding activation and other costs. Actual farmers have their own factors.</p></div>
      <p>Farmers start at level 1 plus one level per {XP_PER_LEVEL} XP, capped at level {MAX_FARMER_LEVEL}. The XP output bonus rises linearly from 0% to 20%. Completion XP is capped at the farmer’s remaining capacity; completion HC is independent of that XP cap.</p><p>Deliveries exchange crops for HC at the displayed customer quote. Orders have finite quantities and daily limits, refreshing at midnight UTC. Selling crop inventory is separate from the HC awarded for completing a grow.</p></section>
      <section id="guide-land" tabIndex={-1}><span className="guide-kicker">06 / LAND</span><h2>Room to grow</h2><p>Land supplies growing spots and an output modifier. These are the expansion options in the current farm interface. Prices use local demo ETH.</p><div className="guide-table"><table><caption>Available farm expansion tiers</caption><thead><tr><th>Land</th><th>Spots</th><th>Output</th><th>Demo ETH</th></tr></thead><tbody>{ALPHA_PLOT_TIERS.map(key => { const p = PLOT_TIERS[key]; return <tr key={key}><th>{p.label}</th><td>{p.slots}</td><td>{p.yieldBonus}×</td><td>{p.priceEth}</td></tr>; })}</tbody></table></div></section>
      <section id="guide-access" tabIndex={-1}><span className="guide-kicker">07 / CLUB ACCESS</span><h2>Your first roots</h2><p>The Club Access page displays the current application status, requirements, and campaign links. Applying does not guarantee selection. Social actions are subject to review.</p><p>Whitelist allocation, deadline, mint date, price, and final launch terms remain unannounced. The existing demo catalog size is not the whitelist allocation.</p><button className="guide-cta" onClick={() => go('/whitelist')}>View Club Access ↗</button></section>
      <section id="guide-status" tabIndex={-1}><span className="guide-kicker">08 / WHAT IS READY</span><h2>Project status</h2><dl className="guide-status"><dt>Playable local demo</dt><dd>Farm exploration, farmer roster, planting, watering, harvest, customer deliveries, land expansion, and XP progression.</dd><dt>Prepared, not connected</dt><dd>Gameplay contract code and an automation runner exist in the project. Live collection ownership checks and blockchain settlement are not integrated into this farm.</dd><dt>Not yet decided</dt><dd>Final NFT art, mint terms, production collection integration, and final economic balance. The proposed OpenSea collection workflow still requires its chain and collection details.</dd></dl><p>Browser saves can be lost if you clear site data or change devices. The current game is a local single-player experience; customer orders are simulated, and automatic collection relies on the app running or reopening.</p><p>Tables on this page read the same catalog and balance settings as the game. Explanations describe the current local implementation; prepared contracts may differ. This is not an independent security audit.</p></section>
      <section id="guide-faq" tabIndex={-1}><span className="guide-kicker">09 / FAQ</span><h2>Before you plant</h2>{[
        ['Does recruiting mint an NFT?', 'No. Recruitment creates a local demo farmer. Production minting is not connected.'],
        ['Can I withdraw HC or sell my demo crops for money?', 'No cash withdrawal or live trading is connected. HC and harvested grams are local game balances.'],
        ['Does rare clothing improve harvests?', 'No accessory bonuses have been finalized. Current output uses the farmer’s assigned rarity, XP, strain, land, and water.'],
        ['Will my demo progress carry into launch?', 'A migration has not been announced. Treat this progress as local playtesting.'],
        ['Does this guide lock the final rules?', 'No. It describes the current demo. Launch rules and collection details will be published separately when finalized.'],
      ].map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</section>
      <footer>Cloud 9 Farm Club · Field Guide · Current demo rules</footer>
    </article></div>
  </main>;
}
